from django.urls import path
from .views import registrar_estudiante, cargar_excel, login_view, subir_reporte, salir, reportes_estudiante, reportes_puesto_puntaje, reportes_observaciones, generar_imagenes_reportes,generar_reporte, lista_estudiantes, editar_estudiante, eliminar_estudiante, agregar_observacion, eliminar_estudiantes_masivo, generar_imagenes_reportes_por_fecha, seleccionar_fecha_generacion, generar_graficos_todos_estudiantes, cargar_asistencias, generar_reporte_asistencia, prueba, generar_todo_reporte, descargar_reporte, descargar_reportes_zip, generar_reporte_asistencia_todos, descargar_reportes_asistencia_zip

urlpatterns = [
    path('', reportes_puesto_puntaje, name='home'),
    path('cargar_asistencias/', cargar_asistencias, name='subir_asistencia'),
    path('cargar-excel/', cargar_excel, name='cargar_excel'),
    path('descargar-reporte/', descargar_reporte, name='descargar_reporte'),
    path('descargar-reportes/', descargar_reportes_zip, name='descargar_reportes_zip'),
    path('descargar-asistencias/', descargar_reportes_asistencia_zip, name='descargar_reportes_asistencias_zip'),
    path('estudiantes/', lista_estudiantes, name='lista_estudiantes'),
    path('estudiantes/eliminar-masivo/', eliminar_estudiantes_masivo, name='eliminar_estudiantes_masivo'),
    path('estudiantes/<int:estudiante_id>/observaciones/', agregar_observacion, name='agregar_observacion'),
    path('estudiantes/editar/<int:pk>/', editar_estudiante, name='editar_estudiante'),
    path('estudiantes/eliminar/<int:pk>/', eliminar_estudiante, name='eliminar_estudiante'),
    path('generar_imagenes_fecha/<fecha>/', generar_imagenes_reportes_por_fecha, name='generar_imagenes_fecha'),
    path('generar_imagenes_reportes/', generar_imagenes_reportes, name='generar_img_carpetas'),
    path("generar_reporte/", generar_reporte, name="generar_reporte"),
    path('generar_reporte_todos/', generar_reporte_asistencia_todos, name='generar_asistencia_todos'),
    path('generar_todo_reporte/', generar_todo_reporte, name='generar_todo_reporte'),
    path('login/', login_view, name='login'),
    path('observaciones/', reportes_observaciones, name='observaciones'),
    path('prueba/', prueba, name='prueba'),
    path('generar_graficos_todos/', generar_graficos_todos_estudiantes, name='generar_graficos_todos'),
    path('reporte_asistencia/', generar_reporte_asistencia, name='reporte_asistencia'),
    path('registrar/', registrar_estudiante, name='registrar_estudiante'),
    path('reportes_estudiante/', reportes_estudiante, name = 'reportes_estudiante'),
    path('salir/', salir, name='salir'),
    path('seleccionar_fecha_reporte/', seleccionar_fecha_generacion, name='seleccionar_fecha_generacion'),
    path('subir_reporte/', subir_reporte, name='subir_reporte'),
]