# Generated by Django 5.1.3 on 2025-03-01 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('ID_Estudiante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=150, unique=True)),
                ('contraseña', models.CharField(max_length=255)),
                ('tipo_estudiante', models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador')], default='estudiante', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('IDReporte', models.AutoField(primary_key=True, serialize=False)),
                ('Rv_1', models.IntegerField()),
                ('Rv_2', models.IntegerField()),
                ('Rm_1', models.IntegerField()),
                ('Rm_2', models.IntegerField()),
                ('Ar_1', models.IntegerField()),
                ('Ar_2', models.IntegerField()),
                ('Al_1', models.IntegerField()),
                ('Al_2', models.IntegerField()),
                ('Ge_1', models.IntegerField()),
                ('Ge_2', models.IntegerField()),
                ('Tr_1', models.IntegerField()),
                ('Tr_2', models.IntegerField()),
                ('Fi_1', models.IntegerField()),
                ('Fi_2', models.IntegerField()),
                ('Qu_1', models.IntegerField()),
                ('Qu_2', models.IntegerField()),
                ('Bi_1', models.IntegerField()),
                ('Bi_2', models.IntegerField()),
                ('Le_1', models.IntegerField()),
                ('Le_2', models.IntegerField()),
                ('Lit_1', models.IntegerField()),
                ('Lit_2', models.IntegerField()),
                ('Hi_1', models.IntegerField()),
                ('Hi_2', models.IntegerField()),
                ('Gf_1', models.IntegerField()),
                ('Gf_2', models.IntegerField()),
                ('Fil_1', models.IntegerField()),
                ('Fil_2', models.IntegerField()),
                ('Psi_1', models.IntegerField()),
                ('Psi_2', models.IntegerField()),
                ('Ec_1', models.IntegerField()),
                ('Ec_2', models.IntegerField()),
                ('fecha_de_examen', models.DateField()),
                ('Observacion', models.CharField(max_length=200)),
                ('puesto', models.IntegerField()),
                ('KK_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='login.estudiante')),
            ],
        ),
    ]
