# Generated by Django 5.1.3 on 2025-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ID_Estudiante',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
