# Generated by Django 5.1.3 on 2025-04-09 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_estudiante_id_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='ID_Estudiante',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('ID_Reporte', models.AutoField(primary_key=True, serialize=False)),
                ('Fecha', models.DateField(default='0000-00-00')),
                ('Ingreso_mana', models.CharField(default='NM', max_length=5)),
                ('Salida_mana', models.CharField(default='NM', max_length=5)),
                ('Ingreso_tarde', models.CharField(default='NM', max_length=5)),
                ('Salida_tarde', models.CharField(default='NM', max_length=5)),
                ('Ingreso_noche', models.CharField(default='NM', max_length=5)),
                ('Salida_noche', models.CharField(default='NM', max_length=5)),
                ('Observacion', models.CharField(default='NM', max_length=30)),
                ('KK_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='login.estudiante')),
            ],
        ),
    ]
