# Generated by Django 5.1.3 on 2025-04-09 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_alter_estudiante_id_estudiante_asistencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
