# Generated by Django 5.1.3 on 2025-05-09 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nivel',
            field=models.IntegerField(choices=[(30, 'Semillero'), (90, 'Pre')], default=90),
        ),
    ]
