# Generated by Django 5.1.3 on 2025-05-09 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_reporte_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporte',
            name='nivel',
        ),
    ]
