# Generated by Django 5.1.3 on 2025-05-09 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_reporte_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='nivel',
            field=models.CharField(choices=[('semillero', 'Semillero'), ('pre', 'Pre')], default='pre', max_length=20),
        ),
    ]
