# Generated by Django 5.1.3 on 2025-05-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_reporte_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='nivel',
            field=models.CharField(choices=[(30, 'Semillero'), (90, 'Pre')], default=90, max_length=20),
        ),
    ]
