# Generated by Django 5.1.3 on 2025-05-19 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_alter_reporte_nivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='nivel',
            field=models.IntegerField(choices=[(30, 'Semillero'), (90, 'Pre')], default=90),
        ),
    ]
