# Generated by Django 5.1.3 on 2025-05-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_reporte_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='reporte_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
