# Generated by Django 5.1.3 on 2025-05-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_estudiante_reporte_actualizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='carrera',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ciudad',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='colegio',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='facebook',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='grado',
            field=models.IntegerField(choices=[(1, '1° de Secundaria'), (2, '2° de Secundaria'), (3, '3° de Secundaria'), (4, '4° de Secundaria'), (5, '5° de Secundaria'), (6, 'Egresado')], default=1),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='instagram',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numCelular',
            field=models.CharField(default='', max_length=9),
        ),
    ]
