# Generated by Django 5.1.3 on 2025-05-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_estudiante_carrera_estudiante_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='actualizado',
            field=models.CharField(choices=[('actualizado', 'Actualizado'), ('desactualizado', 'Desactualizado')], default='desactualizado', max_length=20),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Observacion',
            field=models.CharField(default='', max_length=200),
        ),
    ]
