# Generated by Django 5.1.3 on 2025-05-27 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_estudiante_actualizado_alter_reporte_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asistencia',
            name='Ingreso_mana',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Ingreso_noche',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Ingreso_tarde',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Salida_mana',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Salida_noche',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='Salida_tarde',
        ),
    ]
