# Generated by Django 5.1.3 on 2025-05-27 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_asistencia_ingreso_mana_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='Hora',
            field=models.CharField(default='00:00', max_length=5),
        ),
    ]
