# Generated by Django 5.1.3 on 2025-05-27 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_asistencia_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='Modalidad',
            field=models.CharField(default='PRESENCIAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='Observacion',
            field=models.CharField(default='', max_length=30),
        ),
    ]
