# Generated by Django 5.1.3 on 2025-05-30 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_asistencia_modalidad_alter_asistencia_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableControl',
            fields=[
                ('ID_Variable', models.AutoField(primary_key=True, serialize=False)),
                ('Rm_Pre', models.IntegerField(default=15)),
                ('Rv_Pre', models.IntegerField(default=15)),
                ('Ar_Pre', models.IntegerField(default=5)),
                ('Al_Pre', models.IntegerField(default=5)),
                ('Geom_Pre', models.IntegerField(default=4)),
                ('Trig_Pre', models.IntegerField(default=4)),
                ('Fi_Pre', models.IntegerField(default=5)),
                ('Qui_Pre', models.IntegerField(default=5)),
                ('Bio_Pre', models.IntegerField(default=9)),
                ('Le_Pre', models.IntegerField(default=6)),
                ('Lit_Pre', models.IntegerField(default=6)),
                ('Hi_Pre', models.IntegerField(default=3)),
                ('Geog_Pre', models.IntegerField(default=2)),
                ('Fil_Pre', models.IntegerField(default=2)),
                ('Psi_Pre', models.IntegerField(default=2)),
                ('Ec_Pre', models.IntegerField(default=2)),
                ('Rm_Sem', models.IntegerField(default=10)),
                ('Rv_Sem', models.IntegerField(default=10)),
                ('Ar_Sem', models.IntegerField(default=5)),
                ('Al_Sem', models.IntegerField(default=5)),
                ('Geom_Sem', models.IntegerField(default=0)),
                ('Trig_Sem', models.IntegerField(default=0)),
                ('Fi_Sem', models.IntegerField(default=0)),
                ('Qui_Sem', models.IntegerField(default=0)),
                ('Bio_Sem', models.IntegerField(default=0)),
                ('Le_Sem', models.IntegerField(default=0)),
                ('Lit_Sem', models.IntegerField(default=5)),
                ('Hi_Sem', models.IntegerField(default=0)),
                ('Geog_Sem', models.IntegerField(default=0)),
                ('Fil_Sem', models.IntegerField(default=0)),
                ('Psi_Sem', models.IntegerField(default=0)),
                ('Ec_Sem', models.IntegerField(default=0)),
                ('EntradaManana', models.TimeField(default=(7, 0))),
                ('SalidaManana', models.TimeField(default=(15, 0))),
                ('EntradaTarde', models.TimeField(default=(15, 1))),
                ('SalidaTarde', models.TimeField(default=(19, 59))),
                ('EntradaAmanecida', models.TimeField(default=(20, 0))),
                ('SalidaAmanecida', models.TimeField(default=(6, 59))),
            ],
        ),
    ]
