# Generated by Django 5.1.3 on 2025-06-02 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0016_variablecontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutorados', to='login.estudiante'),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_estudiante',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador'), ('tutor', 'Tutor')], default='estudiante', max_length=20),
        ),
    ]
