# Generated by Django 5.1.3 on 2025-06-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_variablecontrol_preg_corr_con_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variablecontrol',
            name='Preg_Corr_Con',
            field=models.FloatField(default=6),
        ),
        migrations.AlterField(
            model_name='variablecontrol',
            name='Preg_Corr_Raz',
            field=models.FloatField(default=8),
        ),
        migrations.AlterField(
            model_name='variablecontrol',
            name='Preg_Inc_Con',
            field=models.FloatField(default=0.51),
        ),
        migrations.AlterField(
            model_name='variablecontrol',
            name='Preg_Inc_Raz',
            field=models.FloatField(default=0.51),
        ),
    ]
