# Generated by Django 5.1.3 on 2025-06-05 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_alter_variablecontrol_preg_corr_con_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporte',
            name='reporte_actualizado',
            field=models.BooleanField(default=False),
        ),
    ]
