# Generated by Django 5.1.3 on 2025-06-13 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_reporte_reporte_actualizado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Bio_Pre',
            new_name='Bi_Pre',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Bio_Sem',
            new_name='Bi_Sem',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Geom_Pre',
            new_name='Ge_Pre',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Geog_Sem',
            new_name='Ge_Sem',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Geog_Pre',
            new_name='Gf_Pre',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Geom_Sem',
            new_name='Gf_Sem',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Qui_Pre',
            new_name='Qu_Pre',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Qui_Sem',
            new_name='Qu_Sem',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Trig_Pre',
            new_name='Tr_Pre',
        ),
        migrations.RenameField(
            model_name='variablecontrol',
            old_name='Trig_Sem',
            new_name='Tr_Sem',
        ),
    ]
