# Generated by Django 5.1.3 on 2025-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_rename_bio_pre_variablecontrol_bi_pre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte',
            name='Observacion',
            field=models.CharField(default='', max_length=600),
        ),
    ]
