# Generated by Django 5.1.3 on 2025-06-26 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_alter_reporte_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='fechaCumple',
            field=models.DateField(default='1000-01-01'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='gmail',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='numCel2',
            field=models.CharField(default='', max_length=9),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='ruc',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_estudiante',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador'), ('tutor', 'Tutor'), ('profesor', 'profesor')], default='estudiante', max_length=20),
        ),
        migrations.CreateModel(
            name='curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCurso', models.CharField(choices=[('Rv', 'Razonamiento Verbal'), ('Rm', 'Razonamiento Matemático'), ('Ar', 'Aritmética'), ('Al', 'Álgebra'), ('Ge', 'Geometría'), ('Tr', 'Trigonometría'), ('Fi', 'Física'), ('Qu', 'Química'), ('Bi', 'Biología'), ('Le', 'Lenguaje'), ('Lit', 'Literbatura'), ('Hi', 'Historia'), ('Gf', 'Geografía'), ('Fil', 'Filosofía'), ('Psi', 'Psicología'), ('Ec', 'Ecología')], max_length=40)),
                ('estudiante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos', to='login.estudiante')),
            ],
        ),
    ]
