# Generated by Django 5.1.3 on 2025-06-26 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0023_estudiante_fechacumple_estudiante_gmail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='nombreCurso',
            field=models.CharField(choices=[('Rv', 'Razonamiento Verbal'), ('Rm', 'Razonamiento Matemático'), ('Ar', 'Aritmética'), ('Al', 'Álgebra'), ('Ge', 'Geometría'), ('Tr', 'Trigonometría'), ('Fi', 'Física'), ('Qu', 'Química'), ('Bi', 'Biología'), ('Le', 'Lenguaje'), ('Lit', 'Literatura'), ('Hi', 'Historia'), ('Gf', 'Geografía'), ('Fil', 'Filosofía'), ('Psi', 'Psicología'), ('Ec', 'Ecología')], max_length=40),
        ),
    ]
