# Generated by Django 5.1.3 on 2025-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_alter_curso_nombrecurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='fechaCumple',
            field=models.DateField(default='1930-01-01'),
        ),
    ]
