# Generated by Django 5.1.3 on 2025-06-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_alter_estudiante_fechacumple'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='tipo_estudiante',
            field=models.CharField(choices=[('estudiante', 'Estudiante'), ('administrador', 'Administrador'), ('tutor', 'Tutor'), ('profesor', 'Profesor')], default='estudiante', max_length=20),
        ),
    ]
