# Generated by Django 5.1.3 on 2025-09-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0026_alter_estudiante_tipo_estudiante'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='costo_hora',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='reporte',
            name='Observacion',
            field=models.CharField(default='', max_length=1500),
        ),
    ]
